import { Agent } from './agent.model';

export const AGENTS: Agent[] = [
  {
    id: 1,
    name: 'Sova',
    origin: 'Rússia',
    function: 'Initiator',
    staff: 'i am the hunter!',
    name_c:'Alexander (Sasha) Novikov',
  },
  {
    id: 2,
    name: 'Cypher ',
    origin: 'Marrocos',
    function: 'Controller',
    staff: 'Nothing can hide from me.',
    name_c:'Amir El Amari',
  },
  {
    id: 3,
    name: 'Killjoy ',
    origin: 'Germany',
    function: 'Sentinel',
    staff: `Everyone take notes and then we'll do it again.`,
    name_c:'Klara Böhringer',
  },
  {
    id: 4,
    name: 'Omen ',
    origin: 'Unknown',
    function: 'Controller',
    staff: `Keep yourself together!`,
    name_c:'Unknown',
  },
  {
    id: 5,
    name: 'Viper ',
    origin: 'United States',
    function: 'Controller',
    staff: `If any of you die, I lose the bet with Brimstone. So don't embarrass me like that, please.`,
    name_c:'Sabine Callas',
  },
  {
    id: 6,
    name: 'Brimstone ',
    origin: 'United States',
    function: 'Controller',
    staff: `That's how the boss does it.`,
    name_c:'Liam Byrne',
  },
  {
    id: 7,
    name: 'Phoenix  ',
    origin: 'UK',
    function: 'Duelist',
    staff: `Omen wins by fear, don't let it get to you.`,
    name_c:'Jamie Adeyemi',
  },
  {
    id: 8,
    name: 'Jett  ',
    origin: 'South Korea',
    function: 'Duelist',
    staff: `Who needs training dummies when you have real (silly) dummies.`,
    name_c:'Sunwoo Han',
  },
  {
    id: 9,
    name: 'Reyna  ',
    origin: 'México',
    function: 'Duelist',
    staff: `Raze, good! never lose your voice.`,
    name_c: 'Zyanya Mondragón',
  },
  {
    id: 10,
    name: 'Raze ',
    origin: 'Brazil',
    function: 'Duelist',
    staff: `We're here because we're the best, don't forget that`,
    name_c:'Tayane Alves',
  },
];
